# Stage 1: Build the application
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Create the final image
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/monitor-sensors-1.0.0.jar /app/monitor-sensors.jar
EXPOSE 8092
ENTRYPOINT ["java", "-jar", "monitor-sensors.jar"]